#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

## husky task runner examples -------------------
## Note : for local installation use 'dotnet' prefix. e.g. 'dotnet husky'

## run all tasks
#husky run

### run all tasks with group: 'group-name'
#husky run --group group-name

## run task with name: 'task-name'
#husky run --name task-name

## pass hook arguments to task
#husky run --args "$1" "$2"

## or put your custom commands -------------------
#echo 'Husky.Net is awesome!'
exit 0

STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep ".cs$" || true))

if [[ "${STAGED_FILES}" == "" ]]; then
  printf "\nNo cs files were committed so no analyse.\n"
  exit 0
fi

PROJECTS=($(find * -name *.csproj))

echo "roslynator on solution"

echo "${STAGED_FILES[@]}"
roslynator fix --exclude Core/Migrations/* --include "${STAGED_FILES[@]}" 

ROSLYNATOR_EXIT="$?"

# Re-add files since they may have been fixed
git add "${STAGED_FILES[@]}"

if [[ "${ROSLYNATOR_EXIT}" == 0 ]]; then
  printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
else
  printf "\n\033[41mCOMMIT FAILED:\033[0m Fix roslynator errors and try again\n"
  exit 1
fi

exit $?
